config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'posts#index'
  resources :posts
  post '/posts/:post_id/comments' => 'comments#create'
  delete '/comments/:comment_id'=>'comments#destroy',as: 'destoy_comment'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  # 검증(model validation)
  validates :title, presence: {message: "제목을 입력해주세요."},
                    length: {maximum: 30,
                            too_long: "제목은 %{count}자 이내로 입력해주세요." }
  validates :content, presence: {message: "내용을 입력해주세요."}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  load_and_authorize_resource
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        # 저장이 되었을 경우에 실행
        # flash[:notice] = "글 작성이 완료되었습니다."
        # redirect_to '/'
        format.html { redirect_to '/', notice: '글 작성완료!' }
      else
        # 저장이 실패했을 경우에(validation) 걸렸을 때 실행
        # flash[:alert] = "글 작성이 실패했습니다."
        # redirect_to new_post_path
        format.html { render :new }
        format.json { render json: @post.errors }
      end
    end
  end

  def show
    @comments = @post.comments
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to @post, notice: '글 수정완료!'}
      else
        format.html { render :edit }
        format.json { render json: @post.error }
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to "/"
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%# form_for @post do |f| %>
  <%# f.error_messages %>
  <%# f.text_field :title %>
  <%# f.text_area :content %>
  <%# f.submit %>
<%# end %>

<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h1>수정해</h1>
<%= render 'form' %>
<!--
<form action="/posts/<%#@post.id%>" method="post">
  <input type="text" name="title" value="<%#@post.title%>"/> <br />
  <textarea name="content"><%#@post.content%></textarea> <br />
  <input type="hidden" name="_method" value="put" />
  <input type="hidden" name="authenticity_token" value="<%#form_authenticity_token%>">
  <input type="submit" />
</form> -->

<!-- <%# form_tag("/posts/#{@post.id}", method: 'put') do %>
  <%# text_field_tag :title, @post.title %>
  <%# text_area_tag :content, @post.content %>
  <%# submit_tag "뿅!"%>
<%# end %> -->

app/views/posts/index.html.erb
<%= link_to '글쓰기', new_post_path, class: "btn btn-warning" %>
<% @posts.each do |post| %>
  <p>작성자 : <%= post.user.email %></p>
  <p><%= post.id %>번째 글</p>
  <p>제목 : <%= post.title %></p>
  <p>내용 : <%= post.content %></p>
  <%= link_to '글보기', post, class: "btn btn-primary" %>
  <hr />
<% end %>
<div class="d-flex justify-content-center">
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>글 써</h1>
<%= render 'form' %>
<!-- <form action="/posts" method="post">
  <input type="text" name="title" /> <br />
  <textarea name="content"></textarea> <br />
  <input type="hidden" name="authenticity_token" value="<%#form_authenticity_token%>">
  <input type="submit" />
</form> -->

<%# form_tag('/posts', method: 'post') do %>
  <%# text_field_tag :title %>
  <%# text_area_tag :content %>
  <%# submit_tag "뿅!"%>
<%# end %>

app/views/posts/show.html.erb
<h1>글 봐!!</h1>
<%= @post.id %>번째 글
<%= @post.title %>
<%= @post.content %>
<% if can? :edit, @post %>
  <%= link_to '수정하기', edit_post_path(@post) %>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to '삭제하기',
                      @post,
                      method: :delete,
                      data: {confirm: 'are you sure wanna delete?'} %>
<% end %>
<hr />

<form action="/posts/<%= @post.id%>/comments" method="post" data-remote=true> <!--data-remote=true추가됨,아래주석처리한 코드 대신-->
  <input type="text" name="content" /><br />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" />
</form>
<hr />
<div id="comments">
    <% @comments.each do |comment| %>
    <p>
      <%= comment.content %>
      <%= link_to 'delete!!!!!',destoy_comment_path(comment.id), remote:true, method: :delete, class:"delete_comment"%>
      <!--추가코드 remote:true, method: :delete, -->
    </p>
    <hr />
  <% end %>
</div>

<script>
  $('form').on('ajax:success',function(){
    $('input[name="content"]').val('');
  });  
</script>


<!-- https://guides.rorlab.org/working_with_javascript_in_rails.html -->
<!--원래 스크립트코드
<script>
  $('input[type="submit"]').on('click',function(e){
    e.preventDefault();
    alert('start!!');
    $.ajax({url: $('form').attr('action'),
            type: "POST",
            data:{content: $('input[name="content"]').val(),
                  authenticity_token:$('[name="csrf-token"]').attr('content') } ,
            dataType:'script',
            success: function(){
              alert("success!")
              $('input[name="content"]').val('');
            },
            error: function(){
              alert("fail!")
            }
          });
  });

$('.delete_comment').on('click',function(e){
  e.preventDefault();
  alert("startdelete")
  $.ajax({
    url: this.href , //<a></a>
    type: "DELETE",
    data: {authenticity_token:$('[name="csrf-token"]').attr('content')},
    dataType: "script",
    success: function(){
      alert("delete_complete")
    } ,
    error: function(){
      alert("delete_error")
    }
  })
})

</script> -->


<!-- 댓글작성삭제기능
<script>
$('input[type="submit"]').on('click',function(e){  //e=event
  var response=confirm("you wanna submit?");
  if(!response){
    //코드가 실행되려면 response==false
    //e.preventDefault(); //default를 막아주는 코드-submit 되는 것을 막아준다.
    return false; //preventDefault와 같음
  }else{
    //e.stopimmediatePropagation() 동일한 엘리멘트에 있는 다른 이벤트발생 x
  }
});

function checkContentLen(e){
  var content = $('input[name="content"]').val();
  if(content.length<10){
    alert("write down more than 10 lit");
    return false;
  }else{
    alert("excellent!!");
  }
};
$('input[type="submit"]').on("click",checkContentLen);


</script> -->